version: '3.9'

services:
  db:
    image: mysql:8.3
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: shopbot
      MYSQL_ROOT_PASSWORD: tjwnsgh2093
      MYSQL_USER: shopuser               # (선택) 유저 계정 생성
      MYSQL_PASSWORD: tjwnsgh2093 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    build:
      context: .               # Dockerfile이 있는 위치
    container_name: django-app
    command: >
      sh -c "
      sleep 10 &&
      python manage.py migrate &&
      python load_data.py &&
      gunicorn shopbot.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: shopbot.settings

volumes:
  db_data:
      # 필요 시 DATABASE_URL 등 환경변수 추가


